# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mart/mind-matrix-cad

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mart/mind-matrix-cad

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mart/mind-matrix-cad/CMakeFiles /home/mart/mind-matrix-cad//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mart/mind-matrix-cad/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mmc_math

# Build rule for target.
mmc_math: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmc_math
.PHONY : mmc_math

# fast build rule for target.
mmc_math/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/build
.PHONY : mmc_math/fast

#=============================================================================
# Target rules for targets named mmc_geometry

# Build rule for target.
mmc_geometry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmc_geometry
.PHONY : mmc_geometry

# fast build rule for target.
mmc_geometry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/build
.PHONY : mmc_geometry/fast

#=============================================================================
# Target rules for targets named mmc_render

# Build rule for target.
mmc_render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmc_render
.PHONY : mmc_render

# fast build rule for target.
mmc_render/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/build
.PHONY : mmc_render/fast

#=============================================================================
# Target rules for targets named mmc_core

# Build rule for target.
mmc_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmc_core
.PHONY : mmc_core

# fast build rule for target.
mmc_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/build
.PHONY : mmc_core/fast

#=============================================================================
# Target rules for targets named mind_matrix_cad

# Build rule for target.
mind_matrix_cad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mind_matrix_cad
.PHONY : mind_matrix_cad

# fast build rule for target.
mind_matrix_cad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mind_matrix_cad.dir/build.make CMakeFiles/mind_matrix_cad.dir/build
.PHONY : mind_matrix_cad/fast

apps/main_app/main.o: apps/main_app/main.c.o
.PHONY : apps/main_app/main.o

# target to build an object file
apps/main_app/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mind_matrix_cad.dir/build.make CMakeFiles/mind_matrix_cad.dir/apps/main_app/main.c.o
.PHONY : apps/main_app/main.c.o

apps/main_app/main.i: apps/main_app/main.c.i
.PHONY : apps/main_app/main.i

# target to preprocess a source file
apps/main_app/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mind_matrix_cad.dir/build.make CMakeFiles/mind_matrix_cad.dir/apps/main_app/main.c.i
.PHONY : apps/main_app/main.c.i

apps/main_app/main.s: apps/main_app/main.c.s
.PHONY : apps/main_app/main.s

# target to generate assembly for a file
apps/main_app/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mind_matrix_cad.dir/build.make CMakeFiles/mind_matrix_cad.dir/apps/main_app/main.c.s
.PHONY : apps/main_app/main.c.s

src/core/app.o: src/core/app.c.o
.PHONY : src/core/app.o

# target to build an object file
src/core/app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/app.c.o
.PHONY : src/core/app.c.o

src/core/app.i: src/core/app.c.i
.PHONY : src/core/app.i

# target to preprocess a source file
src/core/app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/app.c.i
.PHONY : src/core/app.c.i

src/core/app.s: src/core/app.c.s
.PHONY : src/core/app.s

# target to generate assembly for a file
src/core/app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/app.c.s
.PHONY : src/core/app.c.s

src/core/engine.o: src/core/engine.c.o
.PHONY : src/core/engine.o

# target to build an object file
src/core/engine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/engine.c.o
.PHONY : src/core/engine.c.o

src/core/engine.i: src/core/engine.c.i
.PHONY : src/core/engine.i

# target to preprocess a source file
src/core/engine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/engine.c.i
.PHONY : src/core/engine.c.i

src/core/engine.s: src/core/engine.c.s
.PHONY : src/core/engine.s

# target to generate assembly for a file
src/core/engine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/core/engine.c.s
.PHONY : src/core/engine.c.s

src/geometry/geometry_base.o: src/geometry/geometry_base.c.o
.PHONY : src/geometry/geometry_base.o

# target to build an object file
src/geometry/geometry_base.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/geometry_base.c.o
.PHONY : src/geometry/geometry_base.c.o

src/geometry/geometry_base.i: src/geometry/geometry_base.c.i
.PHONY : src/geometry/geometry_base.i

# target to preprocess a source file
src/geometry/geometry_base.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/geometry_base.c.i
.PHONY : src/geometry/geometry_base.c.i

src/geometry/geometry_base.s: src/geometry/geometry_base.c.s
.PHONY : src/geometry/geometry_base.s

# target to generate assembly for a file
src/geometry/geometry_base.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/geometry_base.c.s
.PHONY : src/geometry/geometry_base.c.s

src/geometry/mesh_nd.o: src/geometry/mesh_nd.c.o
.PHONY : src/geometry/mesh_nd.o

# target to build an object file
src/geometry/mesh_nd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/mesh_nd.c.o
.PHONY : src/geometry/mesh_nd.c.o

src/geometry/mesh_nd.i: src/geometry/mesh_nd.c.i
.PHONY : src/geometry/mesh_nd.i

# target to preprocess a source file
src/geometry/mesh_nd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/mesh_nd.c.i
.PHONY : src/geometry/mesh_nd.c.i

src/geometry/mesh_nd.s: src/geometry/mesh_nd.c.s
.PHONY : src/geometry/mesh_nd.s

# target to generate assembly for a file
src/geometry/mesh_nd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/mesh_nd.c.s
.PHONY : src/geometry/mesh_nd.c.s

src/geometry/parametric.o: src/geometry/parametric.c.o
.PHONY : src/geometry/parametric.o

# target to build an object file
src/geometry/parametric.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/parametric.c.o
.PHONY : src/geometry/parametric.c.o

src/geometry/parametric.i: src/geometry/parametric.c.i
.PHONY : src/geometry/parametric.i

# target to preprocess a source file
src/geometry/parametric.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/parametric.c.i
.PHONY : src/geometry/parametric.c.i

src/geometry/parametric.s: src/geometry/parametric.c.s
.PHONY : src/geometry/parametric.s

# target to generate assembly for a file
src/geometry/parametric.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/parametric.c.s
.PHONY : src/geometry/parametric.c.s

src/geometry/sdf.o: src/geometry/sdf.c.o
.PHONY : src/geometry/sdf.o

# target to build an object file
src/geometry/sdf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/sdf.c.o
.PHONY : src/geometry/sdf.c.o

src/geometry/sdf.i: src/geometry/sdf.c.i
.PHONY : src/geometry/sdf.i

# target to preprocess a source file
src/geometry/sdf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/sdf.c.i
.PHONY : src/geometry/sdf.c.i

src/geometry/sdf.s: src/geometry/sdf.c.s
.PHONY : src/geometry/sdf.s

# target to generate assembly for a file
src/geometry/sdf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_geometry.dir/build.make CMakeFiles/mmc_geometry.dir/src/geometry/sdf.c.s
.PHONY : src/geometry/sdf.c.s

src/math/matrix_nd.o: src/math/matrix_nd.c.o
.PHONY : src/math/matrix_nd.o

# target to build an object file
src/math/matrix_nd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/matrix_nd.c.o
.PHONY : src/math/matrix_nd.c.o

src/math/matrix_nd.i: src/math/matrix_nd.c.i
.PHONY : src/math/matrix_nd.i

# target to preprocess a source file
src/math/matrix_nd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/matrix_nd.c.i
.PHONY : src/math/matrix_nd.c.i

src/math/matrix_nd.s: src/math/matrix_nd.c.s
.PHONY : src/math/matrix_nd.s

# target to generate assembly for a file
src/math/matrix_nd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/matrix_nd.c.s
.PHONY : src/math/matrix_nd.c.s

src/math/projection.o: src/math/projection.c.o
.PHONY : src/math/projection.o

# target to build an object file
src/math/projection.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/projection.c.o
.PHONY : src/math/projection.c.o

src/math/projection.i: src/math/projection.c.i
.PHONY : src/math/projection.i

# target to preprocess a source file
src/math/projection.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/projection.c.i
.PHONY : src/math/projection.c.i

src/math/projection.s: src/math/projection.c.s
.PHONY : src/math/projection.s

# target to generate assembly for a file
src/math/projection.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/projection.c.s
.PHONY : src/math/projection.c.s

src/math/vector_nd.o: src/math/vector_nd.c.o
.PHONY : src/math/vector_nd.o

# target to build an object file
src/math/vector_nd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/vector_nd.c.o
.PHONY : src/math/vector_nd.c.o

src/math/vector_nd.i: src/math/vector_nd.c.i
.PHONY : src/math/vector_nd.i

# target to preprocess a source file
src/math/vector_nd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/vector_nd.c.i
.PHONY : src/math/vector_nd.c.i

src/math/vector_nd.s: src/math/vector_nd.c.s
.PHONY : src/math/vector_nd.s

# target to generate assembly for a file
src/math/vector_nd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_math.dir/build.make CMakeFiles/mmc_math.dir/src/math/vector_nd.c.s
.PHONY : src/math/vector_nd.c.s

src/render/camera.o: src/render/camera.c.o
.PHONY : src/render/camera.o

# target to build an object file
src/render/camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/camera.c.o
.PHONY : src/render/camera.c.o

src/render/camera.i: src/render/camera.c.i
.PHONY : src/render/camera.i

# target to preprocess a source file
src/render/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/camera.c.i
.PHONY : src/render/camera.c.i

src/render/camera.s: src/render/camera.c.s
.PHONY : src/render/camera.s

# target to generate assembly for a file
src/render/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/camera.c.s
.PHONY : src/render/camera.c.s

src/render/renderer.o: src/render/renderer.c.o
.PHONY : src/render/renderer.o

# target to build an object file
src/render/renderer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/renderer.c.o
.PHONY : src/render/renderer.c.o

src/render/renderer.i: src/render/renderer.c.i
.PHONY : src/render/renderer.i

# target to preprocess a source file
src/render/renderer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/renderer.c.i
.PHONY : src/render/renderer.c.i

src/render/renderer.s: src/render/renderer.c.s
.PHONY : src/render/renderer.s

# target to generate assembly for a file
src/render/renderer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/renderer.c.s
.PHONY : src/render/renderer.c.s

src/render/shader.o: src/render/shader.c.o
.PHONY : src/render/shader.o

# target to build an object file
src/render/shader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/shader.c.o
.PHONY : src/render/shader.c.o

src/render/shader.i: src/render/shader.c.i
.PHONY : src/render/shader.i

# target to preprocess a source file
src/render/shader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/shader.c.i
.PHONY : src/render/shader.c.i

src/render/shader.s: src/render/shader.c.s
.PHONY : src/render/shader.s

# target to generate assembly for a file
src/render/shader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/src/render/shader.c.s
.PHONY : src/render/shader.c.s

src/scripting/compiler_bridge.o: src/scripting/compiler_bridge.c.o
.PHONY : src/scripting/compiler_bridge.o

# target to build an object file
src/scripting/compiler_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/compiler_bridge.c.o
.PHONY : src/scripting/compiler_bridge.c.o

src/scripting/compiler_bridge.i: src/scripting/compiler_bridge.c.i
.PHONY : src/scripting/compiler_bridge.i

# target to preprocess a source file
src/scripting/compiler_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/compiler_bridge.c.i
.PHONY : src/scripting/compiler_bridge.c.i

src/scripting/compiler_bridge.s: src/scripting/compiler_bridge.c.s
.PHONY : src/scripting/compiler_bridge.s

# target to generate assembly for a file
src/scripting/compiler_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/compiler_bridge.c.s
.PHONY : src/scripting/compiler_bridge.c.s

src/scripting/formula_parser.o: src/scripting/formula_parser.c.o
.PHONY : src/scripting/formula_parser.o

# target to build an object file
src/scripting/formula_parser.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/formula_parser.c.o
.PHONY : src/scripting/formula_parser.c.o

src/scripting/formula_parser.i: src/scripting/formula_parser.c.i
.PHONY : src/scripting/formula_parser.i

# target to preprocess a source file
src/scripting/formula_parser.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/formula_parser.c.i
.PHONY : src/scripting/formula_parser.c.i

src/scripting/formula_parser.s: src/scripting/formula_parser.c.s
.PHONY : src/scripting/formula_parser.s

# target to generate assembly for a file
src/scripting/formula_parser.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/formula_parser.c.s
.PHONY : src/scripting/formula_parser.c.s

src/scripting/plugin_manager.o: src/scripting/plugin_manager.c.o
.PHONY : src/scripting/plugin_manager.o

# target to build an object file
src/scripting/plugin_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/plugin_manager.c.o
.PHONY : src/scripting/plugin_manager.c.o

src/scripting/plugin_manager.i: src/scripting/plugin_manager.c.i
.PHONY : src/scripting/plugin_manager.i

# target to preprocess a source file
src/scripting/plugin_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/plugin_manager.c.i
.PHONY : src/scripting/plugin_manager.c.i

src/scripting/plugin_manager.s: src/scripting/plugin_manager.c.s
.PHONY : src/scripting/plugin_manager.s

# target to generate assembly for a file
src/scripting/plugin_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/scripting/plugin_manager.c.s
.PHONY : src/scripting/plugin_manager.c.s

src/ui/gui_manager.o: src/ui/gui_manager.c.o
.PHONY : src/ui/gui_manager.o

# target to build an object file
src/ui/gui_manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/gui_manager.c.o
.PHONY : src/ui/gui_manager.c.o

src/ui/gui_manager.i: src/ui/gui_manager.c.i
.PHONY : src/ui/gui_manager.i

# target to preprocess a source file
src/ui/gui_manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/gui_manager.c.i
.PHONY : src/ui/gui_manager.c.i

src/ui/gui_manager.s: src/ui/gui_manager.c.s
.PHONY : src/ui/gui_manager.s

# target to generate assembly for a file
src/ui/gui_manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/gui_manager.c.s
.PHONY : src/ui/gui_manager.c.s

src/ui/panel_console.o: src/ui/panel_console.c.o
.PHONY : src/ui/panel_console.o

# target to build an object file
src/ui/panel_console.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_console.c.o
.PHONY : src/ui/panel_console.c.o

src/ui/panel_console.i: src/ui/panel_console.c.i
.PHONY : src/ui/panel_console.i

# target to preprocess a source file
src/ui/panel_console.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_console.c.i
.PHONY : src/ui/panel_console.c.i

src/ui/panel_console.s: src/ui/panel_console.c.s
.PHONY : src/ui/panel_console.s

# target to generate assembly for a file
src/ui/panel_console.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_console.c.s
.PHONY : src/ui/panel_console.c.s

src/ui/panel_properties.o: src/ui/panel_properties.c.o
.PHONY : src/ui/panel_properties.o

# target to build an object file
src/ui/panel_properties.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_properties.c.o
.PHONY : src/ui/panel_properties.c.o

src/ui/panel_properties.i: src/ui/panel_properties.c.i
.PHONY : src/ui/panel_properties.i

# target to preprocess a source file
src/ui/panel_properties.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_properties.c.i
.PHONY : src/ui/panel_properties.c.i

src/ui/panel_properties.s: src/ui/panel_properties.c.s
.PHONY : src/ui/panel_properties.s

# target to generate assembly for a file
src/ui/panel_properties.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_core.dir/build.make CMakeFiles/mmc_core.dir/src/ui/panel_properties.c.s
.PHONY : src/ui/panel_properties.c.s

third_party/src/gl.o: third_party/src/gl.c.o
.PHONY : third_party/src/gl.o

# target to build an object file
third_party/src/gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/third_party/src/gl.c.o
.PHONY : third_party/src/gl.c.o

third_party/src/gl.i: third_party/src/gl.c.i
.PHONY : third_party/src/gl.i

# target to preprocess a source file
third_party/src/gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/third_party/src/gl.c.i
.PHONY : third_party/src/gl.c.i

third_party/src/gl.s: third_party/src/gl.c.s
.PHONY : third_party/src/gl.s

# target to generate assembly for a file
third_party/src/gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mmc_render.dir/build.make CMakeFiles/mmc_render.dir/third_party/src/gl.c.s
.PHONY : third_party/src/gl.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mind_matrix_cad"
	@echo "... mmc_core"
	@echo "... mmc_geometry"
	@echo "... mmc_math"
	@echo "... mmc_render"
	@echo "... apps/main_app/main.o"
	@echo "... apps/main_app/main.i"
	@echo "... apps/main_app/main.s"
	@echo "... src/core/app.o"
	@echo "... src/core/app.i"
	@echo "... src/core/app.s"
	@echo "... src/core/engine.o"
	@echo "... src/core/engine.i"
	@echo "... src/core/engine.s"
	@echo "... src/geometry/geometry_base.o"
	@echo "... src/geometry/geometry_base.i"
	@echo "... src/geometry/geometry_base.s"
	@echo "... src/geometry/mesh_nd.o"
	@echo "... src/geometry/mesh_nd.i"
	@echo "... src/geometry/mesh_nd.s"
	@echo "... src/geometry/parametric.o"
	@echo "... src/geometry/parametric.i"
	@echo "... src/geometry/parametric.s"
	@echo "... src/geometry/sdf.o"
	@echo "... src/geometry/sdf.i"
	@echo "... src/geometry/sdf.s"
	@echo "... src/math/matrix_nd.o"
	@echo "... src/math/matrix_nd.i"
	@echo "... src/math/matrix_nd.s"
	@echo "... src/math/projection.o"
	@echo "... src/math/projection.i"
	@echo "... src/math/projection.s"
	@echo "... src/math/vector_nd.o"
	@echo "... src/math/vector_nd.i"
	@echo "... src/math/vector_nd.s"
	@echo "... src/render/camera.o"
	@echo "... src/render/camera.i"
	@echo "... src/render/camera.s"
	@echo "... src/render/renderer.o"
	@echo "... src/render/renderer.i"
	@echo "... src/render/renderer.s"
	@echo "... src/render/shader.o"
	@echo "... src/render/shader.i"
	@echo "... src/render/shader.s"
	@echo "... src/scripting/compiler_bridge.o"
	@echo "... src/scripting/compiler_bridge.i"
	@echo "... src/scripting/compiler_bridge.s"
	@echo "... src/scripting/formula_parser.o"
	@echo "... src/scripting/formula_parser.i"
	@echo "... src/scripting/formula_parser.s"
	@echo "... src/scripting/plugin_manager.o"
	@echo "... src/scripting/plugin_manager.i"
	@echo "... src/scripting/plugin_manager.s"
	@echo "... src/ui/gui_manager.o"
	@echo "... src/ui/gui_manager.i"
	@echo "... src/ui/gui_manager.s"
	@echo "... src/ui/panel_console.o"
	@echo "... src/ui/panel_console.i"
	@echo "... src/ui/panel_console.s"
	@echo "... src/ui/panel_properties.o"
	@echo "... src/ui/panel_properties.i"
	@echo "... src/ui/panel_properties.s"
	@echo "... third_party/src/gl.o"
	@echo "... third_party/src/gl.i"
	@echo "... third_party/src/gl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

